---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-kubernetes-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb-kubernetes-operator
  template:
    metadata:
      labels:
        name: mongodb-kubernetes-operator
    spec:
      imagePullSecrets:
      - name: docker-registry-secret
      serviceAccountName: mongodb-kubernetes-operator
      containers:
        - name: mongodb-kubernetes-operator
          image: mongodb/mongodb-kubernetes-operator:latest
          command:
            - /usr/local/bin/entrypoint
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mongodb-kubernetes-operator"
            - name: AGENT_IMAGE # The MongoDB Agent the operator will deploy to manage MongoDB deployments
              value: mongodb/mongodb-agent:10.29.0.6830-1
            - name: VERSION_UPGRADE_HOOK_IMAGE
              value: mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.2
            - name: READINESS_PROBE_IMAGE
              value: mongodb/mongodb-kubernetes-readinessprobe:1.0.1
            - name: MONGODB_IMAGE
              value: mongodb/mongo
