---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-volume-mongodb-pod-resources-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: "nfs-client" 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume-mongodb-pod-resources-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: "nfs-client" 
